# Generated by Django 3.2.15 on 2022-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('FeedBack', models.TextField()),
            ],
        ),
    ]
